// Auto-generated by normalize.ts — do not edit
// This file provides typed access to the generated question pools.

import type { DomainPool, PoolIndex, OptionLetter } from "@/types/contracts";

import cloudConcepts from "./cloud_concepts.json";
import security from "./security.json";
import technologyServices from "./technology_services.json";
import billingPricing from "./billing_pricing.json";

function castPool(questions: unknown[], domain: string): DomainPool {
  return {
    domain: domain as any,
    questions: questions.map((q: any) => ({
      ...q,
      multiSelect: Boolean(q.multiSelect),
      correctAnswers: (q.correctAnswers || []) as OptionLetter[],
      domain: q.domain as any,
    })),
  };
}

export const questionPools: DomainPool[] = [
  castPool(cloudConcepts, "CLOUD_CONCEPTS"),
  castPool(security, "SECURITY"),
  castPool(technologyServices, "TECHNOLOGY_SERVICES"),
  castPool(billingPricing, "BILLING_PRICING"),
];

const totals: Record<string, number> = {};
let grandTotal = 0;
for (const pool of questionPools) {
  totals[pool.domain] = pool.questions.length;
  grandTotal += pool.questions.length;
}

export const poolIndex: PoolIndex = {
  pools: questionPools.map((p) => ({ domain: p.domain, questions: [] })),
  generatedAt: new Date().toISOString(),
  totals: totals as any,
  grandTotal,
};
