// Auto-generated by normalize.ts — do not edit
// Generated at: 2026-07-30T17:24:33.481Z

import type {
  Domain,
  DomainPool,
  NormalizedQuestion,
  PoolIndex,
} from "@/types/contracts";

import metadata from "./index.json";

type QuestionModule = { default: unknown };

function asQuestions(module: QuestionModule): NormalizedQuestion[] {
  return module.default as NormalizedQuestion[];
}

export async function loadQuestionPools(): Promise<DomainPool[]> {
  const [cloudConcepts, security, technologyServices, billingPricing] =
    await Promise.all([
      import("./cloud_concepts.json") as Promise<QuestionModule>,
      import("./security.json") as Promise<QuestionModule>,
      import("./technology_services.json") as Promise<QuestionModule>,
      import("./billing_pricing.json") as Promise<QuestionModule>,
    ]);

  return [
    { domain: "CLOUD_CONCEPTS", questions: asQuestions(cloudConcepts) },
    { domain: "SECURITY", questions: asQuestions(security) },
    { domain: "TECHNOLOGY_SERVICES", questions: asQuestions(technologyServices) },
    { domain: "BILLING_PRICING", questions: asQuestions(billingPricing) },
  ];
}

export const poolIndex: PoolIndex = {
  pools: [
    { domain: "CLOUD_CONCEPTS", questions: [] },
    { domain: "SECURITY", questions: [] },
    { domain: "TECHNOLOGY_SERVICES", questions: [] },
    { domain: "BILLING_PRICING", questions: [] },
  ],
  generatedAt: metadata.generatedAt,
  totals: metadata.totals as Record<Domain, number>,
  grandTotal: metadata.grandTotal,
};
